# Generated by Django 4.2 on 2025-02-22 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article'),
    ]

    operations = [
    ]
